### ISSUE TITLE
Driver Interface?

### ISSUE THREAD

**Issue by mousedownmike** [awslabs/amazon-qldb-driver-go#38]
Are there plans to add an interface for the the QLDBDriver to help with testing?  I think something along the following lines would line up with how things are done in the aws-sdk-go

```Go
package qldbdriveriface

type QLDBDriverAPI interface {
    SetRetryPolicy(rp RetryPolicy)
    Execute(ctx context.Context, fn func(txn Transaction) (interface{}, error)) (interface{}, error)
    GetTableNames(ctx context.Context) ([]string, error)
    Shutdown(ctx context.Context)
}
```

**Comment by mousedownmike** [comment]
With the `QLDBDriverAPI` interface, I'm very close to being able to complete my tests but now I'm unable to mock `qldbdriver.Result` values.  `Transaction` is an interface so I'm able to mock that but I can't create a `qldbdriver.Result` value that will emulate a successful `SELECT` statement (i.e. `result.Next(txn) == true`)..  

My use case is modeled after the [Implementing uniqueness constraints](https://docs.aws.amazon.com/qldb/latest/developerguide/driver-cookbook-golang.html#cookbook-golang.crud.uniqueness-constraints) flow in the developer guide.  If I don't get a result, I perform an `INSERT`, if I do get a result, I perform an `UPDATE`.  The only part of the flow I'm unable to test is the case where a record is actually found.  Is there some way to generate a `Result` that will return `true` on the first `Next(txn)` call?

**Comment by mousedownmike** [comment]
I ended up adding a `Cursor` interface to my fork and I'm able to get my tests working.  It looks like this:

```Go
type Cursor interface {
	Next(txn Transaction) bool
	Err() error
	GetCurrentData() []byte
}
```

That gives us a `Result` that implements `Cursor`.

**Comment by alpian** [comment]
Thanks for reporting this @mousedownmike! We are discussing this at the moment and will respond properly soon. :)

**Comment by simonz-bq** [comment]
Hi @mousedownmike,

Reasoning around this is for testing purposes. We want to ensure that any customers of the Driver can define their own interface for their unit testing won’t have failing unit tests because of changes to the interface. For example, if we needed to add a new method to the interface and if that customer were to upgrade to a newer version of the driver, the mocks would not compile because they would cease to fulfill the contract defined by the interface.

We recommend that the customer of the library defines their own interface for the methods that they need and consume. In this case, the QLDBDriverAPI interface that you have defined would live in your package, containing the methods your package needs, and it would be the Type you assign to the returned object from the constructor of the Driver and any of your functions that require the Driver since it fulfills the contract defined by your interface. You can then use your QLDBDriverAPI for mocking your tests, and if we were to add additional features to the Driver in the future it would not unexpectedly break your tests and your interface would continue to be valid without any changes required if you wished to leverage possible improvements from a newer version of the Driver but didn't need the new method, for example.

Please let us know if you have further questions regarding this.

**Comment by mousedownmike** [comment]
@simonz-bq 

I have ultimately had to use my own fork of this repository in order to effectively develop my tests. Without having the `Result` implementing an interface, I could not find any way to create usable return values from my mock driver.  It could be that I'm missing something, do you have an examples of how you would expect someone to mock up an interaction with the driver?  The cookbook in the documentation is a nice reference but maybe a sample application with tests would shed some more light on what a real-world implementation with tests would look like.

As far as not wanting to break mocks when the driver is upgraded, I actually find this to be a benefit.  I would very much like to know when the driver has changed to the point where my mocks are no longer accurate.  This is a common contract with all of the `aws-sdk-go` packages so I'm not sure why this driver is different.  

I understand AWS is a large organization and each group may have its own guidelines but as a developer, it gets a little confusing when dealing with the subtle differences from one package to another.  This product is delivered under the `awslabs` group but the `aws-sdk-go` documentation strongly encourages its use. Given that, I would think that the patterns used in this product would somewhat align with those found in `aws-sdk-go`.  Not providing an interface seems to go against that.

I certainly don't want to maintain a fork of this driver but the inability to mock the results is forcing me to.  I hope you'll continue to investigate the matter.

Thanks

**Comment by simonz-bq** [comment]
@mousedownmike 

We recommend that library consumers define the interface in the consuming package of the Driver for what methods you need. This ensures the least amount of work on your part when setting up mock classes for testing. It also ensures that you do not have to maintain your tests for any changes to the driver that are unrelated to your own package. 
Here is a quick snippet of an example project with two functions, and a single unit test.

```
// Define the API for QLDB methods that you're going to be using in your package
type MyQldbAPI interface {
	GetTableNames(ctx context.Context) ([]string, error)
	Shutdown(ctx context.Context)
}

// Some example function in your package that uses the QLDB Driver
func Example() {
	awsSession := sdksession.Must(sdksession.NewSession())
	qldbSession := qldbsession.New(awsSession)
	// Without defining your own API
	var qldbDriver *QLDBDriver
	qldbDriver, _ = qldbdriver.New(mockLedgerName, qldbSession)
	defer qldbDriver.Shutdown(context.TODO());
	// Driver can be assigned to your own API type
	var qldbDriverAPI MyQldbAPI
	qldbDriverAPI, _ = qldbdriver.New(mockLedgerName, qldbSession)
	defer qldbDriverAPI.Shutdown(context.TODO())
	// Both can be consumed by GetFirstTableNames, a function in your package
	fmt.Print(GetFirstTableName(qldbDriver))
	fmt.Print(GetFirstTableName(qldbDriverAPI))
}

// A function that takes in the driver to do something, using your defined API
func GetFirstTableName(driver MyQldbAPI) string {
	tableNames, _ := driver.GetTableNames(context.TODO())
	return tableNames[0]
}

// Unit testing the package code using a Mock Driver
type MockDriver struct {
	mock.Mock
}

func (m *MockDriver) GetTableNames(ctx context.Context) ([]string, error) {
	args := m.Called(ctx)
	return args.Get(0).([]string), args.Error(1)
}

func (m *MockDriver) Shutdown(ctx context.Context) {
	return
}

// A test in your package
func TestGetFirstTableName(t *testing.T) {
	exampleTableNames := [2]string{"TableName1", "TableName2"}
	mockDriver := new(MockDriver)
	mockDriver.On("GetTableNames", mock.Anything).Return(exampleTableNames, nil)
	// The MockDriver can also be passed into the function!
	firstTableName := GetFirstTableName(mockDriver)
	assert.Equal(t, firstTableName, "TableName1")
}
```

This way your mocks will never be out of date for the relevant parts to your project. We aim to adhere to semantic versioning to ensure backwards compatibility.

**Comment by mousedownmike** [comment]
@simonz-bq  those methods you show are indeed straightforward to mock but I don't believe they're the primary use of the driver.  The real action (at least for my app) takes place in the `Execute` method and without having `Transaction` implement an interface I can see no way to adequately mock those calls.  Its possible I'm still missing something, do you have an example of how you would mock `Execute` interactions? Should I be using the driver in a different way?

Thanks

**Comment by simonz-bq** [comment]
@mousedownmike are you having trouble testing `execute` itself or the function that is passed through to `execute` that takes in a `Transaction` as a parameter?

**Comment by mousedownmike** [comment]
They seem pretty intertwined so I'm really testing both.  If it helps, here's how I do it with my forked version of the driver.  I've defined `qldbdriver.Cursor` as the interface that `Transaction` implements.

```Go
type MockTransaction struct {
	lastStatements []string
	lastParameters [][]interface{}
	results        []qldbdriver.Cursor
	errors         []error
}

func (m *MockTransaction) Execute(statement string, parameters ...interface{}) (qldbdriver.Cursor, error) {
	m.lastStatements = append(m.lastStatements, statement)
	m.lastParameters = append(m.lastParameters, parameters)
	var e error
	if len(m.errors) > 0 {
		e, m.errors = m.errors[0], m.errors[1:]
	}
	var r qldbdriver.Cursor
	if len(m.results) > 0 {
		r, m.results = m.results[0], m.results[1:]
	}
	return r, e
}
func (m *MockTransaction) BufferResult(_ qldbdriver.Cursor) (*qldbdriver.BufferedResult, error) {
	panic("not used")
}
func (m *MockTransaction) Abort() error {
	panic("not used")
}

type MockQldbDriver struct {
	txn *MockTransaction
}

func (m *MockQldbDriver) Execute(_ context.Context, fn func(txn qldbdriver.Transaction) (interface{}, error)) (interface{}, error) {
	return fn(m.txn)
}
func (m *MockQldbDriver) SetRetryPolicy(_ qldbdriver.RetryPolicy) {
	panic("not used")
}
func (m *MockQldbDriver) GetTableNames(_ context.Context) ([]string, error) {
	panic("not used")
}
func (m *MockQldbDriver) Shutdown(_ context.Context) {
	panic("not used")
}
func TestQldbAuditLog_AddDocument(t *testing.T) {
	var md *MockQldbDriver
	var qs *QldbAuditLog
	var mt *MockTransaction
	var dk DocumentKey
	var doc interface{}
	before := func() {
		mt = &MockTransaction{}
		md = &MockQldbDriver{txn: mt}
		qs = &QldbAuditLog{qldb: md}
		dk = DocumentKey{Partition: meta.Id(), Sort: "Thing_v0000"}
		doc = &thing.ToLog{Id: dk.Partition}
	}
	t.Run("existing_record", func(t *testing.T) {
		before()
		mt.results = append(mt.results, &MockResult{hasNext: true}, nil)
		mt.errors = append(mt.errors, nil, nil)
		e := qs.AddDocument(mockCtx, dk, doc)
		assert.NoError(t, e)
		assert.Len(t, mt.lastStatements, 2)
		assert.True(t, strings.HasPrefix(mt.lastStatements[0], "SELECT a_id FROM Audit"))
		assert.Contains(t, mt.lastParameters[0], dk.Partition)
		assert.Contains(t, mt.lastParameters[0], dk.Sort)
		assert.True(t, strings.HasPrefix(mt.lastStatements[1], "UPDATE Audit"))
		assert.Contains(t, mt.lastParameters[1], dk.Partition)
		assert.Contains(t, mt.lastParameters[1], dk.Sort)
	})

	t.Run("new_record", func(t *testing.T) {
		before()
		mt.results = append(mt.results, &MockResult{hasNext: false}, nil)
		mt.errors = append(mt.errors, nil, nil)
		e := qs.AddDocument(mockCtx, dk, doc)
		assert.NoError(t, e)
		assert.Len(t, mt.lastStatements, 2)
		assert.True(t, strings.HasPrefix(mt.lastStatements[0], "SELECT a_id FROM Audit"))
		assert.True(t, strings.HasPrefix(mt.lastStatements[1], "INSERT INTO Audit"))
		assert.Contains(t, mt.lastParameters[1], doc)
	})
	t.Run("select_error", func(t *testing.T) {
		before()
		mt.results = append(mt.results, nil)
		mt.errors = append(mt.errors, mockError)
		e := qs.AddDocument(mockCtx, dk, doc)
		assert.Error(t, e)
		assert.Len(t, mt.lastStatements, 1)
	})
	t.Run("update_error", func(t *testing.T) {
		before()
		mt.results = append(mt.results, &MockResult{hasNext: true}, nil)
		mt.errors = append(mt.errors, nil, mockError)
		e := qs.AddDocument(mockCtx, dk, doc)
		assert.Error(t, e)
		assert.Len(t, mt.lastStatements, 2)
	})
	t.Run("insert_error", func(t *testing.T) {
		before()
		mt.results = append(mt.results, &MockResult{hasNext: false}, nil)
		mt.errors = append(mt.errors, nil, mockError)
		e := qs.AddDocument(mockCtx, dk, doc)
		assert.Error(t, e)
		assert.Len(t, mt.lastStatements, 2)
	})
}
```

**Comment by alpian** [comment]
Hi @mousedownmike!

The approach the driver is taking is trying to follow the AWS Go SDK v2 approach noted here: https://aws.github.io/aws-sdk-go-v2/docs/unit-testing/. However, your use case is more complex and it seems you want to test the interactions that take place in the driver itself, as opposed over a facade which you then implement.

We are discussing this internally and will come back to you shortly 😄.

**Comment by mousedownmike** [comment]
Thanks @alpian, I just heard about the v2 sdk a few weeks ago and haven't had much time to look into it.  It definitely looks like a departure from the previous patterns so I can see why there's a change with this implementation.  

Without diving too deep, it looks like the "Mocking Paginators" section is the closest to what I would like to do with the Transactions but it isn't really a one to one match since we're passing in a function rather than a struct.  I'll have to dig a bit deeper into the example but I'm still not sure how one would go about mocking the results from the transaction.

For what it's worth, I'm basically implementing `UPSERT` where I check if the record exists at my unique key, if it does, `UPDATE` it and if it doesn't `INSERT` it. I'm not really interested in (re)testing the driver, I'm just interested in testing my application's reactions to what the driver returns.  I'm definitely open to looking at it differently if there's a better way of approaching testing it.

**Comment by simonz-bq** [comment]
@mousedownmike we're still looking into the issue and it's taking some time because we haven't identified a clear solution to the problem. We want to ensure that the approach we take is the right one, since this potentially requires a major version bump. To give some insight, there's 4 plausible approaches that we've come up with.

1. Export and return a Result and BufferedResult interface instead of concrete types from Transaction. The upside of this is that the function passed into `Qldbdriver.Execute` can be tested. The downside is that we cannot add any new features to the Result and BufferedResult types without it being not backwards-compatible, requiring a major version bump for every new feature.
2. Do 1, except every time a new feature is added to the Result types we export a new Interface extending the existing one with the new function(s) in it. The upside of this is the same as 1, with the additional benefit of being backwards compatible. The downside of this is that type checking and casting would be a requirement for using new features, discoverability of features would strictly be documentation-based, and the amount of new interfaces will become excessive as more features are introduced.
3. Create helper methods to create mock, but concrete versions of the Result types so they can be returned in unit testing by the Transaction. The downside of this is that such functions do not fit very well with the intended purpose of the qldbdriver package.
4. Do not support testing of the function passed into `Qldbdriver.Execute`. Although unfortunate, 100% testing coverage is not always feasible and we do not currently have a solution that does not introduce new problems. We recommend logic within the function passed into `Qldbdriver.Execute` be simple to reduce risk without testing; most of the complex logic here is tested by QLDB. Then, quickly return what you need (which can be mocked on the Driver level) as soon as it's available so that complex logic of your library can live outside of the function and be tested as you desire.

Out of these possible options, are there any that you would find preferable? If you have any suggestions for a path we haven't considered that would be very helpful as well!

**Comment by mousedownmike** [comment]
Option 1 would be my preference and is pretty close to what I'm doing in my fork.  Is it very likely that the Result and BufferedResult interfaces will need to change?  If so, can whatever those changes are be implemented soon?  If they are required in the future, it seems like a major version bump would be appropriate and shouldn't be avoided.  

I don't think 2 and 3 are great alternatives just to avoid a version upgrade.

Option 4 would lead me to continue using a fork.  I'm usually suspicious of my own code when I'm unable to test it and almost always find other ways to achieve the same goal while supporting testing.  For many of the use cases where QLDB will be used, I think the ability to thoroughly and repeatedly test will be critical to adoption.  

Generics are coming and I wonder if their implementation might eliminate the need for substantial changes to the Result interfaces.  I have not looked at the proposal in any detail and it still has a ways to go but it might be something to consider and likely something that will require a major version bump anyway.

**Comment by simonz-bq** [comment]
@mousedownmike we have decided to proceed with option 1. We will be making these changes to this repository in the near future, alongside changing the logging interface, so you can point your dependencies on this Github repository instead of maintaining your own fork. 

We won't be making an official release with those changes for a little while since they require a major version bump, and we have some things in the pipeline coming up that are breaking changes that we plan to bundle with the major version release.

Would this unblock you and alleviate the current issue of having to maintain your own fork?

**Comment by mousedownmike** [comment]
@simonz-bq that is great news! I have my code rolled out to production so I will keep using my fork in that code but I will happily test any pre-release code when you have it ready.  When it's time for the major version bump, I'll stop using the fork.  Let me know if you track against a different issue, otherwise, I'll follow the changes here.

**Comment by simonz-bq** [comment]
Hi @mousedownmike,

This is a simplified code snippet that shows testing of a function passed through to Execute that's now enabled by the changes we're making. Could you confirm that the changes allows you to unit test what you wanted? Transaction and Result are now interfaces, that mockTransaction and mockResult implement in our test scenario.

`// Your upsert method that can be passed into QLDBDriver.Execute()
func upsert(txn Transaction) (interface{}, error) {
	res, _ := txn.Execute("SELECT * FROM Table WHERE ID = '12345'")
	if res.Next(txn) {
		txn.Execute("UPDATE Table SET Name = 'Foo' WHERE ID = '12345'")
	} else {
		txn.Execute("INSERT INTO Person <<{'Name' : 'Foo', 'ID' : '12345'}>>")
	}
	return nil, nil
}

type mockTransaction struct {
	mock.Mock
}

func (m *mockTransaction) Execute(statement string, parameters ...interface{}) (Result, error) {
	args := m.Called(statement, parameters)
	return args.Get(0).(Result), args.Error(1)
}

func (m *mockTransaction) BufferResult(res Result) (BufferedResult, error) {
	panic("not used")
}

func (m *mockTransaction) Abort() error {
	panic("not used")
}

type mockResult struct {
	mock.Mock
}

func (r *mockResult) Next(txn Transaction) bool {
	args := r.Called(txn)
	return args.Get(0).(bool)
}

func (r *mockResult) GetCurrentData() []byte {
	panic("not used")
}

func (r *mockResult) GetConsumedIOs() *IOUsage {
	panic("not used")
}

func (r *mockResult) GetTimingInformation() *TimingInformation {
	panic("not used")
}

func (r *mockResult) Err() error {
	panic("not used")
}

func TestUpsert(t *testing.T) {
	// Document already exists (update)
	mockTxn := new(mockTransaction)
	mockRes := new(mockResult)
	mockRes.On("Next", mockTxn).Return(true).Once()
	mockTxn.On("Execute", "SELECT * FROM Table WHERE ID = '12345'", mock.Anything).Return(mockRes, nil)
	mockTxn.On("Execute", "UPDATE Table SET Name = 'Foo' WHERE ID = '12345'", mock.Anything).Return(mockRes, nil)
	upsert(mockTxn)

	mockTxn.AssertCalled(t,"Execute", "UPDATE Table SET Name = 'Foo' WHERE ID = '12345'", mock.Anything)
	mockTxn.AssertNotCalled(t,"Execute", "INSERT INTO Person <<{'Name' : 'Foo', 'ID' : '12345'}>>", mock.Anything)

	// Document did not exist (insert)
	mockRes.On("Next", mockTxn).Return(false).Once()
	mockTxn.On("Execute", "INSERT INTO Person <<{'Name' : 'Foo', 'ID' : '12345'}>>", mock.Anything).Return(mockRes, nil)
	upsert(mockTxn)

	mockTxn.AssertCalled(t,"Execute", "INSERT INTO Person <<{'Name' : 'Foo', 'ID' : '12345'}>>", mock.Anything)
}`

**Comment by mousedownmike** [comment]
@simonz-bq I'm in the middle of a move but I will make reviewing this a priority as soon as I get my office put together. I hope that will be this week but it might not be until the weekend. Thank you for the effort here, I look forward to giving it a try.
